<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Resources\Picture\ApplicationIcon.ico" />
    <Content Include="Resources\Picture\PreviewImage.png" />
    <Content Include="Resources\Picture\TemplateIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Picture\ApplicationIcon.png" />
  </ItemGroup>

</Project>
