<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <EnforceCodeStyleInBuild>True</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <ApplicationIcon>ApplicationIcon.ico</ApplicationIcon>
    <AssemblyVersion>1.7.2026.8</AssemblyVersion>
    <FileVersion>1.7.2026.8</FileVersion>
    <Authors>Lifeprojects.de</Authors>
    <Company>MinimalWPF</Company>
    <Product>MinimalWPF</Product>
    <Description>MinimalWPF NET10 V7 Template </Description>
    <PackageId>MinimalWPF</PackageId>
    <AssemblyName>MinimalWPF</AssemblyName>
    <AssemblyTitle>MinimalWPF</AssemblyTitle>
    <RootNamespace>MinimalWPF</RootNamespace>
    <UseWindowsForms>True</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="ApplicationIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Picture\ApplicationIcon.ico" />
    <Resource Include="Resources\Picture\ApplicationIcon.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Beispiele\EventAggregator\" />
    <Folder Include="Beispiele\SyntaxBox\" />
    <Folder Include="TemplateCore\Controls\FolderPicker\" />
    <Folder Include="_Template\" />
    <Folder Include="Resources\Localization\" />
    <Folder Include="TemplateCore\EventAggregator\" />
    <Folder Include="TemplateCore\HtmlTextBlock\HtmlConverter\" />
    <Folder Include="TemplateCore\HtmlTextBlock\Formatters\" />
    <Folder Include="TemplateCore\ValueObjectTyp\" />
    <Folder Include="TemplateCore\Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Beispiele\Factory\DialogServiceUC.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Beispiele\Factory\NeuUC.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
